myshop/cart/urls.py
from django.urls import path, re_path

from . import views
app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('cart-add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart-remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),


    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path, re_path
from . import views

app_name = "orders"
urlpatterns = [
    path('order-create/', views.order_create, name='order_create'),
]


myshop/shop/urls.py

from django.urls import path, re_path
from . import views

app_name = "shop"
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product-list-by-category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]


myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/orders/models.py
from django.db import models

from shop.models import Product


class Order(models.Model):

    name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = '订单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    class Meta:
        verbose_name = '订单明细'
        verbose_name_plural = verbose_name

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify
 
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True,blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = '商品分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def save(self, *args, **kargs): 
        self.slug = slugify(self.name) 
        super(Category, self).save(*args, **kargs)
#由于URL中有参数，就需要配置URL反向解析
#这样就为模型的对象配置好了用于反向解析URL的方法，我们已经知道，
#-->>get_absolute_url()是很好的获取具体对象规范化URL的方法
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True,blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        verbose_name = '商品'
        verbose_name_plural = verbose_name        

    def __str__(self):
        return self.name
    def save(self, *args, **kargs): 
        self.slug = slugify(self.name) 
        super(Product, self).save(*args, **kargs)
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

myshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 1001)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


    #quantity = forms.IntegerField(min_value=1)

myshop/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'address']


myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm



@require_POST 
def cart_add(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request): 
    cart = Cart(request)
    
    for item in cart:

        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})

    return render(request, 'cart/detail.html', locals())

#添加、更新、删除及展示的视图
#{{"数量":"xx", "price":"xx", "product":"xx"，"update_quantity_form":"xxxx","total_price":"xxx"},  ...}

myshop/orders/views.py
from django.shortcuts import render
from .tasks import order_created
from .models import OrderItem
from .forms import OrderCreateForm

from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
#验证通过之后执行order = form.save()创建新订单对象并写入数据库

            for item in cart:

                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # 成功生成OrderItem之后清除购物车
            cart.clear()
            # 启动异步任务
            order_created.delay(order.id)
            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', locals())

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', locals())


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',locals())

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    你的购物车 
{% endblock %}

{% block content %}
    <h1>你的购物车 </h1>
    <table class="cart">
        <thead>
            <tr>
                <th>图片</th>
                <th>产品</th>
                <th>数量</th>
                <th>移除</th>
                <th>单价</th>                
                <th>总价</th>
            </tr>
        </thead>
        <tbody> 
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>

                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post"> 
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="更新">
                        {% csrf_token %}
                    </form>
                </td>

                <td><a href="{% url 'cart:cart_remove' product.id %}">删除</a></td>
                <td class="num">￥{{ item.price }}</td>
                <td class="num">￥{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">￥{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">继续购物 </a>
        <a href="{% url "orders:order_create" %}" class="button">结帐 </a>        

    </p>

{% endblock %}



myshop/orders/templates/orders/order/create.html

{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    结算
{% endblock %}

{% block content %}

    <h1>结算</h1>
    
    <div class="order-info">
        <h3>你的订单</h3>
        <ul>
            {% for item in cart %} 
                <li>{{ item.quantity }}x {{ item.product.name }} <span>${{ item.total_price }}</span></li>
            {% endfor %}
        </ul>
        <p>Total: ￥{{ cart.get_total_price }}</p>
    </div>
<form action="." method="post" class="order-form" novalidate>    
<table>
<tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" maxlength="50" required id="id_name" /></td></tr>

<tr><th><label for="id_email">Email:</label></th><td><input type="email" name="email" maxlength="254" required id="id_email" /></td></tr>

<tr><th><label for="id_address">Address:</label></th><td><input type="address" name="address" maxlength="254" required id="id_address" /></td></tr>
</table>
<p><input type="submit" value="结算"></p>
        {% csrf_token %}
    </form>


    
{% endblock %} 




myshop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
    谢谢你 
{% endblock %}

{% block content %}
    <h1>谢谢你</h1>
    <p>您的订单已成功完成。您的订单号是 <strong>{{ order.id }}</strong>.</p>
{% endblock %}

myshop/shop/templates/shop/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}我的商店 {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">我的商店</a>
    </div>
    <div id="subheader">
        <div class="cart">
            
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    您的购物车: 
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} 商品, ￥{{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
                  


        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>


</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load staticfiles %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %} 
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>


        <p class="price">￥{{ product.price }}</p>


        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="添加到购物车">
        </form>
         
        {{ product.description|linebreaks }}
    </div>
{% endblock %}


        
        
        

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load staticfiles %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}商品{% endif %}
{% endblock %}

{% block content %}

    <div id="sidebar">
        <h3>种类</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">全部</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>


    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}商品{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ￥{{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}